# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React App

on:
  push:
    branches: [prod_front]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      #- name: pm2 NodeJS Daemon
      #  run: pm2 restart test

      # Je n'arrive pas à update la CD_Conrado...
      #- name: Move the Build to /var/www/portfolio
      #  run: CD_Conrado_Portfolio_Front
        
      - name: Delete the content of /var/www/cmonpanierbio
        run: rm -r /var/www/cmonpanierbio
        
      - name: Copy the content of the deployed App to /var/www/cmonpanier
        run: cp -r /home/debian/deploy/Conrado-Portfolio/Conrado-Portfolio/build/* /var/www/cmonpanierbio/
